### ISSUE TITLE
Road Map

### ISSUE THREAD

**Issue by zyyv** [zyyv/magic-color#14]
- [x]  #13 
- [x] #15
- [x] #17
- [x] #18
- [ ] `unplugin` for contrast tools
- [ ] into devtools panel
- [x] #19
- [ ] Docs with vitepress
- [x] #22
- [x] #23
- [x] #27
- [x] #29
